version: '3.1'
services:
  db:
    build:
      context: ./mysql/
      dockerfile: dockerfile
    volumes:
      - ./data/prestashop_DB:/var/lib/mysql
    restart: always
    networks:
      - prestashop_network

  prestashop:
    build:
      context: ./Prestashop/
      dockerfile: dockerfile
    volumes:
      - ./data/prestashop:/var/www/html
    depends_on:
      - db
    ports:
      - 80:80
    restart: always
    networks:
      - prestashop_network

networks:
  prestashop_network:
    external: true