FROM prestashop/prestashop:1.7

ENV DB_SERVER=db
ENV DB_USER=root
ENV DB_PASSWD=password
ENV DB_PREFIX=ps_
ENV DB_NAME=prestashop
ENV PS_LANGUAGE=es 
ENV PS_COUNTRY=CL
ENV ADMIN_MAIL=ddfernandezvap@gmail.com
ENV ADMIN_PASSWD=password

COPY mycert.crt /etc/ssl/certs/mycert.crt
COPY mykey.key /etc/ssl/private/mykey.key

RUN a2enmod ssl && \
    a2ensite default-ssl && \
    sed -i \
    -e 's|SSLCertificateFile.*|SSLCertificateFile /etc/ssl/certs/mycert.crt|g' \
    -e 's|SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/ssl/private/mykey.key|g' \
    /etc/apache2/sites-available/default-ssl.conf
    
EXPOSE 443