FROM prestashop/prestashop:1.7

ENV DB_SERVER=db
ENV DB_USER=root
ENV DB_PASSWD=password
ENV DB_PREFIX=ps_
ENV DB_NAME=prestashop
ENV PS_LANGUAGE=es 
ENV PS_COUNTRY=CL
ENV ADMIN_MAIL=ddfernandezvap@gmail.com
ENV ADMIN_PASSWD=password

EXPOSE 80