<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4qcsbb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4qcsbb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerW4qcsbb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerW4qcsbb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerW4qcsbb\appProdProjectContainer([
    'container.build_hash' => 'W4qcsbb',
    'container.build_id' => 'd74689e0',
    'container.build_time' => 1718391193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW4qcsbb');
